### ISSUE TITLE
Login and Registration error handling

### ISSUE THREAD

**Issue by F4R105** [F4R105/git_collab#1]
When redirecting user after login failure or registration failure, let us use the **same variable** (msg). @ludanadeodatus nmeona kuna sehem umetumia msg na sehem nyngn message.

**Comment by ludanadeodatus** [comment]
$msg nimetumia kwenye redirects zinazoenda kwenye login (hii nimemuiga hamis), ila $message ni zile zinazobaki kwenye page yangu...
