### ISSUE TITLE
Addition in form inputs element

### ISSUE THREAD

**Issue by Hamisi-shingwa** [F4R105/git_collab#15]
Please style field_element is class of element created via javascript to prompty client once leave required form field  empty when he/she filll the form

**Comment by F4R105** [comment]
we already have an element which displays feedback messages i.e feedback_container, there is no need to create another element for the same job
i suggest you add your feedback message to p tag inside feedback_container as innerHTML or textContent and add 'show' class to feedback container to display the error

**Comment by Hamisi-shingwa** [comment]
Nilijua 2 😃😃
