### ISSUE TITLE
API request

### ISSUE THREAD

**Issue by Hamisi-shingwa** [F4R105/git_collab#16]
Naombeni access ya registered user nijaribu kumzuia new member kuweka username ya mtu alie register tyr

**Comment by F4R105** [comment]
Iyo si inabd iwe separate php file?!!

**Comment by ludanadeodatus** [comment]
sijakupata

**Comment by Hamisi-shingwa** [comment]
Mnipe access ya user walio register tyr nataka niwapate kwa javscript waweza fanya kwa separate file km alivyosugest kajubu au utumie user_list.php u echo wale user na waencode ktk json format

**Comment by Cyxteen** [comment]
unataka hii list mda gan?
before kulogin or after

**Comment by Hamisi-shingwa** [comment]
Hii taitumia akt akirejister. Note kwamba logic yangu sio Muhim saana
nachotaka tu Ni kumprompty mtu akiwa anaregister km hiyo username aiwekayo
ishakuwa na mtu au not

**Comment by Cyxteen** [comment]
the smoothest way ya kupata izo data ni kupitia ajax. ivyo the page does not have to load

**Comment by Cyxteen** [comment]
au kama ni php it's doable

**Comment by Hamisi-shingwa** [comment]
Tatumia Ajax ndio naomben mnifechie hzo data kwnye page flan(server) mm nitumie ajax kutuma request ktika hyo server nipate hzo data ile naombeni ziwe tu encoded ktika json format ithink mtatumia json_encode($data) baada yakuwa mmezipush zoote ktka one array au mfanye mtavyoweza mm nipate tu nijaribu lufanya hcho kitu

**Comment by Cyxteen** [comment]
kwan kuna file limetengenezwa tyr??
au nitengeneze

**Comment by Hamisi-shingwa** [comment]
Bora mtengeneze japo nimeona file la user_list.php sjajua mnafuture nalo gani kwaiyo ningeomba tu mtengeneze lingine

**Comment by Cyxteen** [comment]
tumia user_list, nimemake changes to it ili irudishe usernames tu.
usisahau kupull kwnza

**Comment by Cyxteen** [comment]
@Hamisi-shingwa fanya kupull tena
