### ISSUE TITLE
The need for serious action

### ISSUE THREAD

**Issue by Hamisi-shingwa** [F4R105/git_collab#18]
user_list.php is required in user_account page naomben  mnintengenezee page yangu nyingine au wa user_account aangalie namna nyingine yakuimplement anachotaka

**Comment by F4R105** [comment]
Page ya kuonyesha nini

**Comment by Hamisi-shingwa** [comment]
Nataka page ambayo ita echo list ya registered user nimejaribu kumzuia mtu asijisajiri kwa jina lililo kwisha sajiliwa tayari wamenipa access ya hyo page ya user_list

**Comment by F4R105** [comment]
Mimi sihusiki na user_list

**Comment by Cyxteen** [comment]
Kwan ukitumia iyo user_list vo
